apiVersion: v2
name: validator-plugin-kubescape
description: >-
  validator-plugin-kubescape executes kubescape against your Kubernetes cluster
  and validates the results.
type: application
version: 0.0.7
appVersion: 0.0.2
