apiVersion: validation.spectrocloud.labs/v1alpha1
kind: KubescapeValidator
metadata:
  labels:
    app.kubernetes.io/name: kubescapevalidator
    app.kubernetes.io/instance: kubescapevalidator-sample
    app.kubernetes.io/part-of: validator-plugin-kubescape
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: validator-plugin-kubescape
  name: kubescapevalidator-sample
spec:
  severityLimitRule:
    critical: 0
    unknown: 0

  # Rule to flag CVEs
  flaggedCVERule:
    - "CVE-2022-21698"
