//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubescapeValidator) DeepCopyInto(out *KubescapeValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubescapeValidator.
func (in *KubescapeValidator) DeepCopy() *KubescapeValidator {
	if in == nil {
		return nil
	}
	out := new(KubescapeValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubescapeValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubescapeValidatorList) DeepCopyInto(out *KubescapeValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubescapeValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubescapeValidatorList.
func (in *KubescapeValidatorList) DeepCopy() *KubescapeValidatorList {
	if in == nil {
		return nil
	}
	out := new(KubescapeValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubescapeValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubescapeValidatorSpec) DeepCopyInto(out *KubescapeValidatorSpec) {
	*out = *in
	in.SeverityLimitRule.DeepCopyInto(&out.SeverityLimitRule)
	if in.IgnoredCVERule != nil {
		in, out := &in.IgnoredCVERule, &out.IgnoredCVERule
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FlaggedCVERule != nil {
		in, out := &in.FlaggedCVERule, &out.FlaggedCVERule
		*out = make([]FlaggedCVE, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubescapeValidatorSpec.
func (in *KubescapeValidatorSpec) DeepCopy() *KubescapeValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(KubescapeValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubescapeValidatorStatus) DeepCopyInto(out *KubescapeValidatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubescapeValidatorStatus.
func (in *KubescapeValidatorStatus) DeepCopy() *KubescapeValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(KubescapeValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeverityLimitRule) DeepCopyInto(out *SeverityLimitRule) {
	*out = *in
	if in.Critical != nil {
		in, out := &in.Critical, &out.Critical
		*out = new(int)
		**out = **in
	}
	if in.High != nil {
		in, out := &in.High, &out.High
		*out = new(int)
		**out = **in
	}
	if in.Medium != nil {
		in, out := &in.Medium, &out.Medium
		*out = new(int)
		**out = **in
	}
	if in.Low != nil {
		in, out := &in.Low, &out.Low
		*out = new(int)
		**out = **in
	}
	if in.Negligible != nil {
		in, out := &in.Negligible, &out.Negligible
		*out = new(int)
		**out = **in
	}
	if in.Unknown != nil {
		in, out := &in.Unknown, &out.Unknown
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeverityLimitRule.
func (in *SeverityLimitRule) DeepCopy() *SeverityLimitRule {
	if in == nil {
		return nil
	}
	out := new(SeverityLimitRule)
	in.DeepCopyInto(out)
	return out
}
